"""empty message

Revision ID: 595503777c01
Revises: cb5813521116
Create Date: 2026-04-25 19:28:48.788253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '595503777c01'
down_revision: Union[str, Sequence[str], None] = 'cb5813521116'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('balance', sa.Float(), server_default='0.0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'balance')
    # ### end Alembic commands ###
