"""empty message

Revision ID: cb5813521116
Revises: b5e3298f5cfb
Create Date: 2026-04-24 23:58:10.153471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5813521116'
down_revision: Union[str, Sequence[str], None] = 'b5e3298f5cfb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coins', sa.Column('coingecko_id', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'coins', ['coingecko_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'coins', type_='unique')
    op.drop_column('coins', 'coingecko_id')
    # ### end Alembic commands ###
