"""add added_at to portfolio

Revision ID: e44fe3664f0c
Revises: 595503777c01
Create Date: 2026-04-25 20:27:54.167985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44fe3664f0c'
down_revision: Union[str, Sequence[str], None] = '595503777c01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('added_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'added_at')
    # ### end Alembic commands ###
